name: cgpacal
description: A new Flutter project.
publish_to: 'none' # Remove or change this if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # Uncomment and add asset paths if you have images or fonts
  # assets:
  #   - assets/images/
  #   - assets/icons/

  # fonts:
  #   - family: YourFont
  #     fonts:
  #       - asset: fonts/YourFont-Regular.ttf
  #       - asset: fonts/YourFont-Bold.ttf
  #         weight: 700
